# Generated by Django 3.1 on 2020-09-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TituloPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descricao', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('PG', 'Pago'), ('AP', 'A Pagar')], default='AP', max_length=2)),
                ('classificacao', models.ForeignKey(null='true', on_delete=django.db.models.deletion.RESTRICT, to='fluxocaixa.classificacaopagar')),
                ('formapagamento', models.ForeignKey(null='true', on_delete=django.db.models.deletion.RESTRICT, to='fluxocaixa.formapagamento')),
            ],
        ),
    ]
