# Generated by Django 3.1 on 2020-09-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxocaixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TituloReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expectativa', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descricao', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('RC', 'Recebido'), ('AR', 'A Receber')], default='AR', max_length=2)),
                ('classificacao', models.ForeignKey(null='true', on_delete=django.db.models.deletion.RESTRICT, to='fluxocaixa.classificacaoreceber')),
                ('formapagamento', models.ForeignKey(null='true', on_delete=django.db.models.deletion.RESTRICT, to='fluxocaixa.formapagamento')),
            ],
        ),
    ]
