# Generated by Django 3.1 on 2020-09-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxocaixa', '0004_auto_20200919_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorinicial', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
